name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Update Code & Restart Docker
        run: |
          cd /root/CuanTrack
          git config --global --add safe.directory /root/CuanTrack
          
          # Update
          git pull origin main
          docker compose up -d --build
          docker compose exec -T app php artisan migrate --force
          docker compose exec -T app php artisan optimize:clear