name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Update Code & Restart Docker
        run: |

          cd /CuanTrack
          git config --global --add safe.directory /CuanTrack
          git pull origin main
          docker compose up -d --build
          docker compose exec -T app php artisan migrate --force
          # F. Bersihkan cache
          docker compose exec -T app php artisan optimize:clear